### ISSUE TITLE
Bundle won't work with Arduino IDE 1.6

### ISSUE THREAD

**Issue by der-onkel** [nasser/arduino.tmbundle#33]
Hi there,

Arduino bundle doesn't work with Arduino IDE 1.6 for Java 7.
Reasons:
- make is missing in the App bundle
- no official CMD line support in Arduino IDE 1.6 for Java 7

:-(

**Comment by carpii** [comment]
Maybe this doesnt work on the Java 7 version, but if anyone else wants to get this bundle working on default OSX Arduino, just edit the bundle items (accurate as of Arduino IDE 1.6.3)...

Upload

```
#!/bin/bash
echo "<pre>"
/Applications/Arduino.app/Contents/MacOS/Arduino --upload "$TM_FILEPATH"
echo "</pre>"
```

Compile

```
#!/bin/bash
echo "<pre>"
/Applications/Arduino.app/Contents/MacOS/Arduino --verify "$TM_FILEPATH"
echo "</pre>"
```

Its a bit clumsy but seems to work at least

**Comment by Steveosanchez** [comment]
This worked for me thanks!!!

**Comment by jacken** [comment]
Thanks! Now I can finally work in my favourite editor!

**Comment by der-onkel** [comment]
Works for me!
